<template><div><h3 id="数据类型" tabindex="-1"><a class="header-anchor" href="#数据类型"><span>数据类型</span></a></h3>
<p>计算机顾名思义就是可以做数学计算的机器，因此，计算机程序理所当然地可以处理各种数值。但是，计算机能处理的远不止数值，还可以处理文本、图形、音频、视频、网页等各种各样的数据，不同的数据，需要定义不同的数据类型。在Python中，能够直接处理的数据类型有以下几种：</p>
<h4 id="整数" tabindex="-1"><a class="header-anchor" href="#整数"><span>整数</span></a></h4>
<p>Python可以处理任意大小的整数，当然包括负整数，在程序中的表示方法和数学上的写法一模一样，例如：<code v-pre>1</code>，<code v-pre>100</code>，<code v-pre>-8080</code>，<code v-pre>0</code>，等等。</p>
<p>计算机由于使用二进制，所以，有时候用十六进制表示整数比较方便，十六进制用<code v-pre>0x</code>前缀和0-9，a-f表示，例如：<code v-pre>0xff00</code>，<code v-pre>0xa5b4c3d2</code>，等等。</p>
<p>对于很大的数，例如<code v-pre>10000000000</code>，很难数清楚0的个数。Python允许在数字中间以<code v-pre>_</code>分隔，因此，写成<code v-pre>10_000_000_000</code>和<code v-pre>10000000000</code>是完全一样的。十六进制数也可以写成<code v-pre>0xa1b2_c3d4</code>。</p>
<h4 id="浮点数" tabindex="-1"><a class="header-anchor" href="#浮点数"><span>浮点数</span></a></h4>
<p>浮点数也就是小数，之所以称为浮点数，是因为按照科学记数法表示时，一个浮点数的小数点位置是可变的，比如，1.23x10<sup>9</sup>和12.3x10<sup>8</sup>是完全相等的。浮点数可以用数学写法，如<code v-pre>1.23</code>，<code v-pre>3.14</code>，<code v-pre>-9.01</code>，等等。但是对于很大或很小的浮点数，就必须用科学计数法表示，把10用e替代，1.23x10<sup>9</sup>就是<code v-pre>1.23e9</code>，或者<code v-pre>12.3e8</code>，0.000012可以写成<code v-pre>1.2e-5</code>，等等。</p>
<p>整数和浮点数在计算机内部存储的方式是不同的，整数运算永远是精确的（除法难道也是精确的？是的！），而浮点数运算则可能会有四舍五入的误差。</p>
<h4 id="字符串" tabindex="-1"><a class="header-anchor" href="#字符串"><span>字符串</span></a></h4>
<p>字符串是以单引号<code v-pre>'</code>或双引号<code v-pre>&quot;</code>括起来的任意文本，比如<code v-pre>'abc'</code>，<code v-pre>&quot;xyz&quot;</code>等等。请注意，<code v-pre>''</code>或<code v-pre>&quot;&quot;</code>本身只是一种表示方式，不是字符串的一部分，因此，字符串<code v-pre>'abc'</code>只有<code v-pre>a</code>，<code v-pre>b</code>，<code v-pre>c</code>这3个字符。如果<code v-pre>'</code>本身也是一个字符，那就可以用<code v-pre>&quot;&quot;</code>括起来，比如<code v-pre>&quot;I'm OK&quot;</code>包含的字符是<code v-pre>I</code>，<code v-pre>'</code>，<code v-pre>m</code>，空格，<code v-pre>O</code>，<code v-pre>K</code>这6个字符。</p>
<p>如果字符串内部既包含<code v-pre>'</code>又包含<code v-pre>&quot;</code>怎么办？可以用转义字符<code v-pre>\</code>来标识，比如：</p>
<div class="language- line-numbers-mode" data-highlighter="shiki" data-ext="" style="--shiki-light:#383A42;--shiki-dark:#abb2bf;--shiki-light-bg:#FAFAFA;--shiki-dark-bg:#282c34"><pre class="shiki shiki-themes one-light one-dark-pro vp-code" v-pre=""><code class="language-"><span class="line"><span>'I\'m \"OK\"!'</span></span></code></pre>
<div class="line-numbers" aria-hidden="true" style="counter-reset:line-number 0"><div class="line-number"></div></div></div><p>表示的字符串内容是：</p>
<div class="language-python line-numbers-mode" data-highlighter="shiki" data-ext="python" style="--shiki-light:#383A42;--shiki-dark:#abb2bf;--shiki-light-bg:#FAFAFA;--shiki-dark-bg:#282c34"><pre class="shiki shiki-themes one-light one-dark-pro vp-code" v-pre=""><code class="language-python"><span class="line"><span style="--shiki-light:#383A42;--shiki-dark:#ABB2BF">I</span><span style="--shiki-light:#50A14F;--shiki-dark:#98C379">'m "OK"!</span></span></code></pre>
<div class="line-numbers" aria-hidden="true" style="counter-reset:line-number 0"><div class="line-number"></div></div></div><p>转义字符<code v-pre>\</code>可以转义很多字符，比如<code v-pre>\n</code>表示换行，<code v-pre>\t</code>表示制表符，字符<code v-pre>\</code>本身也要转义，所以<code v-pre>\\</code>表示的字符就是<code v-pre>\</code>，可以在Python的交互式命令行用<code v-pre>print()</code>打印字符串看看：</p>
<div class="language-python line-numbers-mode" data-highlighter="shiki" data-ext="python" style="--shiki-light:#383A42;--shiki-dark:#abb2bf;--shiki-light-bg:#FAFAFA;--shiki-dark-bg:#282c34"><pre class="shiki shiki-themes one-light one-dark-pro vp-code" v-pre=""><code class="language-python"><span class="line"><span style="--shiki-light:#0184BC;--shiki-dark:#56B6C2">print</span><span style="--shiki-light:#383A42;--shiki-dark:#ABB2BF">(</span><span style="--shiki-light:#50A14F;--shiki-dark:#98C379">'I</span><span style="--shiki-light:#0184BC;--shiki-dark:#56B6C2">\'</span><span style="--shiki-light:#50A14F;--shiki-dark:#98C379">m ok.'</span><span style="--shiki-light:#383A42;--shiki-dark:#ABB2BF">)</span></span>
<span class="line"><span style="--shiki-light:#383A42;--shiki-dark:#ABB2BF">I</span><span style="--shiki-light:#50A14F;--shiki-dark:#98C379">'m ok.print('</span><span style="--shiki-light:#383A42;--shiki-dark:#ABB2BF">I\</span><span style="--shiki-light:white;--shiki-dark:#FFFFFF">'m learning\nPython.')</span></span>
<span class="line"><span style="--shiki-light:#383A42;--shiki-dark:#ABB2BF">I</span><span style="--shiki-light:#50A14F;--shiki-dark:#98C379">'m learning</span></span>
<span class="line"><span style="--shiki-light:#383A42;--shiki-dark:#ABB2BF">Python.</span></span>
<span class="line"><span style="--shiki-light:#0184BC;--shiki-dark:#56B6C2">print</span><span style="--shiki-light:#383A42;--shiki-dark:#ABB2BF">(</span><span style="--shiki-light:#50A14F;--shiki-dark:#98C379">'</span><span style="--shiki-light:#0184BC;--shiki-dark:#56B6C2">\\\n\\</span><span style="--shiki-light:#50A14F;--shiki-dark:#98C379">'</span><span style="--shiki-light:#383A42;--shiki-dark:#ABB2BF">)</span></span>
<span class="line"><span style="--shiki-light:#383A42;--shiki-dark:#ABB2BF">\</span></span>
<span class="line"><span style="--shiki-light:#383A42;--shiki-dark:#ABB2BF">\</span></span></code></pre>
<div class="line-numbers" aria-hidden="true" style="counter-reset:line-number 0"><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div></div></div><figure><img src="@source/Studynotes/python/1/assets/20250712_093409_1.png" alt="" tabindex="0" loading="lazy"><figcaption></figcaption></figure>
<p>如果字符串里面有很多字符都需要转义，就需要加很多<code v-pre>\</code>，为了简化，Python还允许用<code v-pre>r''</code>表示<code v-pre>''</code>内部的字符串默认不转义，可以自己试试：</p>
<div class="language-python line-numbers-mode" data-highlighter="shiki" data-ext="python" style="--shiki-light:#383A42;--shiki-dark:#abb2bf;--shiki-light-bg:#FAFAFA;--shiki-dark-bg:#282c34"><pre class="shiki shiki-themes one-light one-dark-pro vp-code" v-pre=""><code class="language-python"><span class="line"><span style="--shiki-light:#0184BC;--shiki-dark:#56B6C2">print</span><span style="--shiki-light:#383A42;--shiki-dark:#ABB2BF">(</span><span style="--shiki-light:#50A14F;--shiki-dark:#98C379">'</span><span style="--shiki-light:#0184BC;--shiki-dark:#56B6C2">\\\t\\</span><span style="--shiki-light:#50A14F;--shiki-dark:#98C379">'</span><span style="--shiki-light:#383A42;--shiki-dark:#ABB2BF">)</span></span>
<span class="line"><span style="--shiki-light:#383A42;--shiki-dark:#ABB2BF">\       </span><span style="--shiki-light:white;--shiki-dark:#FFFFFF">\</span></span>
<span class="line"><span style="--shiki-light:#0184BC;--shiki-dark:#56B6C2">print</span><span style="--shiki-light:#383A42;--shiki-dark:#ABB2BF">(</span><span style="--shiki-light:#A626A4;--shiki-dark:#C678DD">r</span><span style="--shiki-light:#0184BC;--shiki-dark:#E06C75">'</span><span style="--shiki-light:#0184BC;--shiki-dark:#56B6C2">\\\t\\</span><span style="--shiki-light:#0184BC;--shiki-dark:#E06C75">'</span><span style="--shiki-light:#383A42;--shiki-dark:#ABB2BF">)</span></span>
<span class="line"><span style="--shiki-light:#383A42;--shiki-dark:#ABB2BF">\</span><span style="--shiki-light:white;--shiki-dark:#FFFFFF">\\t\\</span></span></code></pre>
<div class="line-numbers" aria-hidden="true" style="counter-reset:line-number 0"><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div></div></div><figure><img src="@source/Studynotes/python/1/assets/20250712_093424_2.png" alt="" tabindex="0" loading="lazy"><figcaption></figcaption></figure>
<p>如果字符串内部有很多换行，用<code v-pre>\n</code>写在一行里不好阅读，为了简化，Python允许用<code v-pre>'''...'''</code>的格式表示多行内容，可以自己试试：</p>
<div class="language-python line-numbers-mode" data-highlighter="shiki" data-ext="python" style="--shiki-light:#383A42;--shiki-dark:#abb2bf;--shiki-light-bg:#FAFAFA;--shiki-dark-bg:#282c34"><pre class="shiki shiki-themes one-light one-dark-pro vp-code" v-pre=""><code class="language-python"><span class="line"><span style="--shiki-light:#0184BC;--shiki-dark:#56B6C2">print</span><span style="--shiki-light:#383A42;--shiki-dark:#ABB2BF">(</span><span style="--shiki-light:#50A14F;--shiki-dark:#98C379">'''line1</span></span>
<span class="line"><span style="--shiki-light:#50A14F;--shiki-dark:#98C379">line2</span></span>
<span class="line"><span style="--shiki-light:#50A14F;--shiki-dark:#98C379">line3'''</span><span style="--shiki-light:#383A42;--shiki-dark:#ABB2BF">)</span></span></code></pre>
<div class="line-numbers" aria-hidden="true" style="counter-reset:line-number 0"><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div></div></div><figure><img src="@source/Studynotes/python/1/assets/20250712_093438_3.png" alt="" tabindex="0" loading="lazy"><figcaption></figcaption></figure>
<p>多行字符串<code v-pre>''' '''</code>还可以在前面加上<code v-pre>r</code>使用，请自行测试：</p>
<figure><img src="@source/Studynotes/python/1/assets/20250712_093514_4.png" alt="" tabindex="0" loading="lazy"><figcaption></figcaption></figure>
<h4 id="布尔值" tabindex="-1"><a class="header-anchor" href="#布尔值"><span>布尔值</span></a></h4>
<p>布尔值和布尔代数的表示完全一致，一个布尔值只有<code v-pre>True</code>、<code v-pre>False</code>两种值，要么是<code v-pre>True</code>，要么是<code v-pre>False</code>，在Python中，可以直接用<code v-pre>True</code>、<code v-pre>False</code>表示布尔值（请注意大小写），也可以通过布尔运算计算出来：</p>
<figure><img src="@source/Studynotes/python/1/assets/20250712_093533_5.png" alt="" tabindex="0" loading="lazy"><figcaption></figcaption></figure>
<p>布尔值可以用<code v-pre>and</code>、<code v-pre>or</code>和<code v-pre>not</code>运算。</p>
<p><code v-pre>and</code>运算是与运算，只有所有都为<code v-pre>True</code>，<code v-pre>and</code>运算结果才是<code v-pre>True</code>：</p>
<figure><img src="@source/Studynotes/python/1/assets/20250712_093543_6.png" alt="" tabindex="0" loading="lazy"><figcaption></figcaption></figure>
<p><code v-pre>or</code>运算是或运算，只要其中有一个为<code v-pre>True</code>，<code v-pre>or</code>运算结果就是<code v-pre>True</code>：</p>
<figure><img src="@source/Studynotes/python/1/assets/20250712_093548_7.png" alt="" tabindex="0" loading="lazy"><figcaption></figcaption></figure>
<p><code v-pre>not</code>运算是非运算，它是一个单目运算符，把<code v-pre>True</code>变成<code v-pre>False</code>，<code v-pre>False</code>变成<code v-pre>True</code>：</p>
<figure><img src="@source/Studynotes/python/1/assets/20250712_093555_8.png" alt="" tabindex="0" loading="lazy"><figcaption></figcaption></figure>
<p>布尔值经常用在条件判断中，比如：</p>
<div class="language-python line-numbers-mode" data-highlighter="shiki" data-ext="python" style="--shiki-light:#383A42;--shiki-dark:#abb2bf;--shiki-light-bg:#FAFAFA;--shiki-dark-bg:#282c34"><pre class="shiki shiki-themes one-light one-dark-pro vp-code" v-pre=""><code class="language-python"><span class="line"><span style="--shiki-light:#383A42;--shiki-dark:#ABB2BF">i</span><span style="--shiki-light:#383A42;--shiki-dark:#56B6C2">=</span><span style="--shiki-light:#383A42;--shiki-dark:#ABB2BF">(</span><span style="--shiki-light:#986801;--shiki-dark:#D19A66">1</span><span style="--shiki-light:#383A42;--shiki-dark:#ABB2BF">)</span></span>
<span class="line"><span style="--shiki-light:#A626A4;--shiki-dark:#C678DD">if</span><span style="--shiki-light:#383A42;--shiki-dark:#ABB2BF"> i</span><span style="--shiki-light:#383A42;--shiki-dark:#56B6C2">>=</span><span style="--shiki-light:#986801;--shiki-dark:#D19A66"> 1</span><span style="--shiki-light:#383A42;--shiki-dark:#ABB2BF">:</span></span>
<span class="line"><span style="--shiki-light:#0184BC;--shiki-dark:#56B6C2">    print</span><span style="--shiki-light:#383A42;--shiki-dark:#ABB2BF">(</span><span style="--shiki-light:#50A14F;--shiki-dark:#98C379">"变量I大于等于1"</span><span style="--shiki-light:#383A42;--shiki-dark:#ABB2BF">)</span></span>
<span class="line"><span style="--shiki-light:#A626A4;--shiki-dark:#C678DD">else</span><span style="--shiki-light:#383A42;--shiki-dark:#ABB2BF">:</span></span>
<span class="line"><span style="--shiki-light:#0184BC;--shiki-dark:#56B6C2">    print</span><span style="--shiki-light:#383A42;--shiki-dark:#ABB2BF">(</span><span style="--shiki-light:#50A14F;--shiki-dark:#98C379">"变量I小于1"</span><span style="--shiki-light:#383A42;--shiki-dark:#ABB2BF">)</span></span></code></pre>
<div class="line-numbers" aria-hidden="true" style="counter-reset:line-number 0"><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div></div></div><figure><img src="@source/Studynotes/python/1/assets/20250712_093622_9.png" alt="" tabindex="0" loading="lazy"><figcaption></figcaption></figure>
<h4 id="空值" tabindex="-1"><a class="header-anchor" href="#空值"><span>空值</span></a></h4>
<p>空值是Python里一个特殊的值，用<code v-pre>None</code>表示。<code v-pre>None</code>不能理解为<code v-pre>0</code>，因为<code v-pre>0</code>是有意义的，而<code v-pre>None</code>是一个特殊的空值。</p>
<p>此外，Python还提供了列表、字典等多种数据类型，还允许创建自定义数据类型，我们后面会继续讲到。</p>
<h3 id="变量" tabindex="-1"><a class="header-anchor" href="#变量"><span>变量</span></a></h3>
<p>变量的概念基本上和初中代数的方程变量是一致的，只是在计算机程序中，变量不仅可以是数字，还可以是任意数据类型。</p>
<p>变量在程序中就是用一个变量名表示了，变量名必须是大小写英文、数字和<code v-pre>_</code>的组合，且不能用数字开头，比如：</p>
<div class="language-python line-numbers-mode" data-highlighter="shiki" data-ext="python" style="--shiki-light:#383A42;--shiki-dark:#abb2bf;--shiki-light-bg:#FAFAFA;--shiki-dark-bg:#282c34"><pre class="shiki shiki-themes one-light one-dark-pro vp-code" v-pre=""><code class="language-python"><span class="line"><span style="--shiki-light:#383A42;--shiki-dark:#ABB2BF">i</span><span style="--shiki-light:#383A42;--shiki-dark:#56B6C2">=</span><span style="--shiki-light:#383A42;--shiki-dark:#ABB2BF">(</span><span style="--shiki-light:#986801;--shiki-dark:#D19A66">1</span><span style="--shiki-light:#383A42;--shiki-dark:#ABB2BF">)</span></span></code></pre>
<div class="line-numbers" aria-hidden="true" style="counter-reset:line-number 0"><div class="line-number"></div></div></div><p>上方变量<code v-pre>i</code>是一个整数。</p>
<div class="language-python line-numbers-mode" data-highlighter="shiki" data-ext="python" style="--shiki-light:#383A42;--shiki-dark:#abb2bf;--shiki-light-bg:#FAFAFA;--shiki-dark-bg:#282c34"><pre class="shiki shiki-themes one-light one-dark-pro vp-code" v-pre=""><code class="language-python"><span class="line"><span style="--shiki-light:#383A42;--shiki-dark:#ABB2BF">t_007 </span><span style="--shiki-light:#383A42;--shiki-dark:#56B6C2">=</span><span style="--shiki-light:#50A14F;--shiki-dark:#98C379"> 'T007'</span></span></code></pre>
<div class="line-numbers" aria-hidden="true" style="counter-reset:line-number 0"><div class="line-number"></div></div></div><p>上方变量<code v-pre>t_007</code>是一个字符串。</p>
<div class="language-python line-numbers-mode" data-highlighter="shiki" data-ext="python" style="--shiki-light:#383A42;--shiki-dark:#abb2bf;--shiki-light-bg:#FAFAFA;--shiki-dark-bg:#282c34"><pre class="shiki shiki-themes one-light one-dark-pro vp-code" v-pre=""><code class="language-python"><span class="line"><span style="--shiki-light:#383A42;--shiki-dark:#ABB2BF">Answer </span><span style="--shiki-light:#383A42;--shiki-dark:#56B6C2">=</span><span style="--shiki-light:#986801;--shiki-dark:#D19A66"> True</span></span></code></pre>
<div class="line-numbers" aria-hidden="true" style="counter-reset:line-number 0"><div class="line-number"></div></div></div><p>上方变量<code v-pre>Answer</code>是一个布尔值<code v-pre>True</code>。</p>
<p>在Python中，等号=是赋值语句，可以把任意数据类型赋值给变量，同一个变量可以反复赋值，而且可以是不同类型的变量，例如：</p>
<div class="language-python line-numbers-mode" data-highlighter="shiki" data-ext="python" style="--shiki-light:#383A42;--shiki-dark:#abb2bf;--shiki-light-bg:#FAFAFA;--shiki-dark-bg:#282c34"><pre class="shiki shiki-themes one-light one-dark-pro vp-code" v-pre=""><code class="language-python"><span class="line"><span style="--shiki-light:#383A42;--shiki-dark:#ABB2BF">a </span><span style="--shiki-light:#383A42;--shiki-dark:#56B6C2">=</span><span style="--shiki-light:#986801;--shiki-dark:#D19A66"> 123</span><span style="--shiki-light:#A0A1A7;--shiki-light-font-style:italic;--shiki-dark:#7F848E;--shiki-dark-font-style:italic"> # a是整数</span></span>
<span class="line"><span style="--shiki-light:#0184BC;--shiki-dark:#56B6C2">print</span><span style="--shiki-light:#383A42;--shiki-dark:#ABB2BF">(a)</span></span>
<span class="line"><span style="--shiki-light:#383A42;--shiki-dark:#ABB2BF">a </span><span style="--shiki-light:#383A42;--shiki-dark:#56B6C2">=</span><span style="--shiki-light:#50A14F;--shiki-dark:#98C379"> 'ABC'</span><span style="--shiki-light:#A0A1A7;--shiki-light-font-style:italic;--shiki-dark:#7F848E;--shiki-dark-font-style:italic"> # a变为字符串</span></span>
<span class="line"><span style="--shiki-light:#0184BC;--shiki-dark:#56B6C2">print</span><span style="--shiki-light:#383A42;--shiki-dark:#ABB2BF">(a)</span></span></code></pre>
<div class="line-numbers" aria-hidden="true" style="counter-reset:line-number 0"><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div></div></div><figure><img src="@source/Studynotes/python/1/assets/20250712_093642_10.png" alt="" tabindex="0" loading="lazy"><figcaption></figcaption></figure>
<p>这种变量本身类型不固定的语言称之为​<em>动态语言</em>​，与之对应的是​<em>静态语言</em>​。静态语言在定义变量时必须指定变量类型，如果赋值的时候类型不匹配，就会报错。例如Java是静态语言，赋值语句如下（// 表示注释）：</p>
<div class="language-python line-numbers-mode" data-highlighter="shiki" data-ext="python" style="--shiki-light:#383A42;--shiki-dark:#abb2bf;--shiki-light-bg:#FAFAFA;--shiki-dark-bg:#282c34"><pre class="shiki shiki-themes one-light one-dark-pro vp-code" v-pre=""><code class="language-python"><span class="line"><span style="--shiki-light:#0184BC;--shiki-dark:#56B6C2">int</span><span style="--shiki-light:#383A42;--shiki-dark:#ABB2BF"> a </span><span style="--shiki-light:#383A42;--shiki-dark:#56B6C2">=</span><span style="--shiki-light:#50A14F;--shiki-dark:#98C379"> "ABC"</span><span style="--shiki-light:#383A42;--shiki-dark:#ABB2BF">; </span><span style="--shiki-light:#383A42;--shiki-dark:#56B6C2">//</span><span style="--shiki-light:#383A42;--shiki-dark:#ABB2BF"> 错误：不能把字符串赋给整型变量</span></span></code></pre>
<div class="line-numbers" aria-hidden="true" style="counter-reset:line-number 0"><div class="line-number"></div></div></div><figure><img src="@source/Studynotes/python/1/assets/20250712_093658_11.png" alt="" tabindex="0" loading="lazy"><figcaption></figcaption></figure>
<p>和静态语言相比，动态语言更灵活，就是这个原因。</p>
<p>请不要把赋值语句的等号等同于数学的等号。比如下面的代码：</p>
<div class="language-python line-numbers-mode" data-highlighter="shiki" data-ext="python" style="--shiki-light:#383A42;--shiki-dark:#abb2bf;--shiki-light-bg:#FAFAFA;--shiki-dark-bg:#282c34"><pre class="shiki shiki-themes one-light one-dark-pro vp-code" v-pre=""><code class="language-python"><span class="line"><span style="--shiki-light:#383A42;--shiki-dark:#ABB2BF">x </span><span style="--shiki-light:#383A42;--shiki-dark:#56B6C2">=</span><span style="--shiki-light:#986801;--shiki-dark:#D19A66"> 10</span></span>
<span class="line"><span style="--shiki-light:#383A42;--shiki-dark:#ABB2BF">x </span><span style="--shiki-light:#383A42;--shiki-dark:#56B6C2">=</span><span style="--shiki-light:#383A42;--shiki-dark:#ABB2BF"> x </span><span style="--shiki-light:#383A42;--shiki-dark:#56B6C2">+</span><span style="--shiki-light:#986801;--shiki-dark:#D19A66"> 2</span></span></code></pre>
<div class="line-numbers" aria-hidden="true" style="counter-reset:line-number 0"><div class="line-number"></div><div class="line-number"></div></div></div><p>如果从数学上理解<code v-pre>x = x + 2</code>那无论如何是不成立的，在程序中，赋值语句先计算右侧的表达式<code v-pre>x + 2</code>，得到结果<code v-pre>12</code>，再赋给变量<code v-pre>x</code>。由于<code v-pre>x</code>之前的值是<code v-pre>10</code>，重新赋值后，<code v-pre>x</code>的值变成<code v-pre>12</code>。</p>
<p>最后，理解变量在计算机内存中的表示也非常重要。当我们写：</p>
<p>时，Python解释器干了两件事情：</p>
<ol>
<li>在内存中创建了一个<code v-pre>'ABC'</code>的字符串；</li>
<li>在内存中创建了一个名为<code v-pre>a</code>的变量，并把它指向<code v-pre>'ABC'</code>。</li>
</ol>
<p>也可以把一个变量<code v-pre>a</code>赋值给另一个变量<code v-pre>b</code>，这个操作实际上是把变量<code v-pre>b</code>指向变量<code v-pre>a</code>所指向的数据，例如下面的代码：</p>
<div class="language-python line-numbers-mode" data-highlighter="shiki" data-ext="python" style="--shiki-light:#383A42;--shiki-dark:#abb2bf;--shiki-light-bg:#FAFAFA;--shiki-dark-bg:#282c34"><pre class="shiki shiki-themes one-light one-dark-pro vp-code" v-pre=""><code class="language-python"><span class="line"><span style="--shiki-light:#383A42;--shiki-dark:#ABB2BF">a </span><span style="--shiki-light:#383A42;--shiki-dark:#56B6C2">=</span><span style="--shiki-light:#50A14F;--shiki-dark:#98C379"> 'ABC'</span></span>
<span class="line"><span style="--shiki-light:#383A42;--shiki-dark:#ABB2BF">b </span><span style="--shiki-light:#383A42;--shiki-dark:#56B6C2">=</span><span style="--shiki-light:#383A42;--shiki-dark:#ABB2BF"> a</span></span>
<span class="line"><span style="--shiki-light:#383A42;--shiki-dark:#ABB2BF">a </span><span style="--shiki-light:#383A42;--shiki-dark:#56B6C2">=</span><span style="--shiki-light:#50A14F;--shiki-dark:#98C379"> 'XYZ'</span></span>
<span class="line"><span style="--shiki-light:#0184BC;--shiki-dark:#56B6C2">print</span><span style="--shiki-light:#383A42;--shiki-dark:#ABB2BF">(b)</span></span></code></pre>
<div class="line-numbers" aria-hidden="true" style="counter-reset:line-number 0"><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div></div></div><p>最后一行打印出变量<code v-pre>b</code>的内容到底是<code v-pre>'ABC'</code>呢还是<code v-pre>'XYZ'</code>？如果从数学意义上理解，就会错误地得出<code v-pre>b</code>和<code v-pre>a</code>相同，也应该是<code v-pre>'XYZ'</code>，但实际上<code v-pre>b</code>的值是<code v-pre>'ABC'</code>，让我们一行一行地执行代码，就可以看到到底发生了什么事：</p>
<p>执行<code v-pre>a = 'ABC'</code>，解释器创建了字符串<code v-pre>'ABC'</code>和变量<code v-pre>a</code>，并把<code v-pre>a</code>指向<code v-pre>'ABC'</code>：</p>
<figure><img src="@source/Studynotes/python/1/assets/20250712_093738_step-1.png" alt="" tabindex="0" loading="lazy"><figcaption></figcaption></figure>
<p>执行<code v-pre>b = a</code>，解释器创建了变量<code v-pre>b</code>，并把<code v-pre>b</code>指向<code v-pre>a</code>指向的字符串<code v-pre>'ABC'</code>：</p>
<figure><img src="@source/Studynotes/python/1/assets/20250712_093748_step-2.png" alt="" tabindex="0" loading="lazy"><figcaption></figcaption></figure>
<p>执行<code v-pre>a = 'XYZ'</code>，解释器创建了字符串'XYZ'，并把<code v-pre>a</code>的指向改为<code v-pre>'XYZ'</code>，但<code v-pre>b</code>并没有更改：</p>
<figure><img src="@source/Studynotes/python/1/assets/20250712_093803_step-3.png" alt="" tabindex="0" loading="lazy"><figcaption></figcaption></figure>
<p>所以，最后打印变量<code v-pre>b</code>的结果自然是<code v-pre>'ABC'</code>了。</p>
<h3 id="常量" tabindex="-1"><a class="header-anchor" href="#常量"><span>常量</span></a></h3>
<p>所谓常量就是不能变的变量，比如常用的数学常数π就是一个常量。在Python中，通常用全部大写的变量名表示常量：</p>
<div class="language-python line-numbers-mode" data-highlighter="shiki" data-ext="python" style="--shiki-light:#383A42;--shiki-dark:#abb2bf;--shiki-light-bg:#FAFAFA;--shiki-dark-bg:#282c34"><pre class="shiki shiki-themes one-light one-dark-pro vp-code" v-pre=""><code class="language-python"><span class="line"><span style="--shiki-light:#383A42;--shiki-dark:#D19A66">PI</span><span style="--shiki-light:#383A42;--shiki-dark:#56B6C2"> =</span><span style="--shiki-light:#986801;--shiki-dark:#D19A66"> 3.14159265359</span></span></code></pre>
<div class="line-numbers" aria-hidden="true" style="counter-reset:line-number 0"><div class="line-number"></div></div></div><p>但事实上<code v-pre>PI</code>仍然是一个变量，Python根本没有任何机制保证<code v-pre>PI</code>不会被改变，所以，用全部大写的变量名表示常量只是一个习惯上的用法，如果你一定要改变变量<code v-pre>PI</code>的值，也没人能拦住你。</p>
<p>最后解释一下整数的除法为什么也是精确的。在Python中，有两种除法，一种除法是<code v-pre>/</code>：</p>
<div class="language-python line-numbers-mode" data-highlighter="shiki" data-ext="python" style="--shiki-light:#383A42;--shiki-dark:#abb2bf;--shiki-light-bg:#FAFAFA;--shiki-dark-bg:#282c34"><pre class="shiki shiki-themes one-light one-dark-pro vp-code" v-pre=""><code class="language-python"><span class="line"><span style="--shiki-light:#0184BC;--shiki-dark:#56B6C2">print</span><span style="--shiki-light:#383A42;--shiki-dark:#ABB2BF">(</span><span style="--shiki-light:#986801;--shiki-dark:#D19A66">10</span><span style="--shiki-light:#383A42;--shiki-dark:#56B6C2"> /</span><span style="--shiki-light:#986801;--shiki-dark:#D19A66"> 3</span><span style="--shiki-light:#383A42;--shiki-dark:#ABB2BF">)</span></span>
<span class="line"><span style="--shiki-light:#986801;--shiki-dark:#D19A66">3.333333</span></span></code></pre>
<div class="line-numbers" aria-hidden="true" style="counter-reset:line-number 0"><div class="line-number"></div><div class="line-number"></div></div></div><figure><img src="@source/Studynotes/python/1/assets/20250712_093819_12.png" alt="" tabindex="0" loading="lazy"><figcaption></figcaption></figure>
<p><code v-pre>/</code>除法计算结果是浮点数，即使是两个整数恰好整除，结果也是浮点数：</p>
<div class="language-python line-numbers-mode" data-highlighter="shiki" data-ext="python" style="--shiki-light:#383A42;--shiki-dark:#abb2bf;--shiki-light-bg:#FAFAFA;--shiki-dark-bg:#282c34"><pre class="shiki shiki-themes one-light one-dark-pro vp-code" v-pre=""><code class="language-python"><span class="line"><span style="--shiki-light:#0184BC;--shiki-dark:#56B6C2">print</span><span style="--shiki-light:#383A42;--shiki-dark:#ABB2BF">(</span><span style="--shiki-light:#986801;--shiki-dark:#D19A66">9</span><span style="--shiki-light:#383A42;--shiki-dark:#56B6C2"> /</span><span style="--shiki-light:#986801;--shiki-dark:#D19A66"> 3</span><span style="--shiki-light:#383A42;--shiki-dark:#ABB2BF">)</span></span>
<span class="line"><span style="--shiki-light:#986801;--shiki-dark:#D19A66">3.0</span></span></code></pre>
<div class="line-numbers" aria-hidden="true" style="counter-reset:line-number 0"><div class="line-number"></div><div class="line-number"></div></div></div><figure><img src="@source/Studynotes/python/1/assets/20250712_093834_13.png" alt="" tabindex="0" loading="lazy"><figcaption></figcaption></figure>
<p>还有一种除法是<code v-pre>//</code>，称为地板除，两个整数的除法仍然是整数：</p>
<div class="language-python line-numbers-mode" data-highlighter="shiki" data-ext="python" style="--shiki-light:#383A42;--shiki-dark:#abb2bf;--shiki-light-bg:#FAFAFA;--shiki-dark-bg:#282c34"><pre class="shiki shiki-themes one-light one-dark-pro vp-code" v-pre=""><code class="language-python"><span class="line"><span style="--shiki-light:#0184BC;--shiki-dark:#56B6C2">print</span><span style="--shiki-light:#383A42;--shiki-dark:#ABB2BF">(</span><span style="--shiki-light:#986801;--shiki-dark:#D19A66">10</span><span style="--shiki-light:#383A42;--shiki-dark:#56B6C2"> //</span><span style="--shiki-light:#986801;--shiki-dark:#D19A66"> 3</span><span style="--shiki-light:#383A42;--shiki-dark:#ABB2BF">)</span></span>
<span class="line"><span style="--shiki-light:#986801;--shiki-dark:#D19A66">3</span></span></code></pre>
<div class="line-numbers" aria-hidden="true" style="counter-reset:line-number 0"><div class="line-number"></div><div class="line-number"></div></div></div><figure><img src="@source/Studynotes/python/1/assets/20250712_093847_14.png" alt="" tabindex="0" loading="lazy"><figcaption></figcaption></figure>
<p>你没有看错，整数的地板除<code v-pre>//</code>永远是整数，即使除不尽。要做结果为浮点数的除法，使用<code v-pre>/</code>就可以。</p>
<p>因为<code v-pre>//</code>除法只取结果的整数部分，所以Python还提供一个余数运算，可以得到两个整数相除的余数：</p>
<div class="language-python line-numbers-mode" data-highlighter="shiki" data-ext="python" style="--shiki-light:#383A42;--shiki-dark:#abb2bf;--shiki-light-bg:#FAFAFA;--shiki-dark-bg:#282c34"><pre class="shiki shiki-themes one-light one-dark-pro vp-code" v-pre=""><code class="language-python"><span class="line"><span style="--shiki-light:#0184BC;--shiki-dark:#56B6C2">print</span><span style="--shiki-light:#383A42;--shiki-dark:#ABB2BF">(</span><span style="--shiki-light:#986801;--shiki-dark:#D19A66">10</span><span style="--shiki-light:#383A42;--shiki-dark:#56B6C2"> %</span><span style="--shiki-light:#986801;--shiki-dark:#D19A66"> 3</span><span style="--shiki-light:#383A42;--shiki-dark:#ABB2BF">)</span></span>
<span class="line"><span style="--shiki-light:#986801;--shiki-dark:#D19A66">1</span></span></code></pre>
<div class="line-numbers" aria-hidden="true" style="counter-reset:line-number 0"><div class="line-number"></div><div class="line-number"></div></div></div><figure><img src="@source/Studynotes/python/1/assets/20250712_093905_15.png" alt="" tabindex="0" loading="lazy"><figcaption></figcaption></figure>
<p>无论整数做<code v-pre>//</code>除法还是取余数，结果永远是整数，所以，整数运算的结果永远是精确的。</p>
</div></template>


